FROM pytorch/pytorch:1.5-cuda10.1-cudnn7-devel
MAINTAINER tongjinle
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get -q -y install openssh-server python-pip python-tk build-essential python-dev libevent-dev python3-dev
RUN apt-get install -y git
RUN apt-get install -y libsndfile1 gcc make autoconf openssl portaudio19-dev python-all-dev python3-all-dev
RUN apt-get install -y vim
RUN mkdir /var/run/sshd
RUN sed "s/without-password/yes/g" /etc/ssh/sshd_config > /etc/ssh/sshd_config2
RUN cp /etc/ssh/sshd_config2 /etc/ssh/sshd_config
RUN echo 'root:root' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade
#RUN git clone https://github.com/NVIDIA/apex;cd apex;pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
RUN rm -rf ~/.cache/pip/*
RUN apt-get clean
RUN service ssh restart
ENV LANG     en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL   en_US.UTF-8
EXPOSE 22 8019 8022 8021 8020 8023 8024 8025 6006 6005 6007 6008 8888 8889 8890 8891 8892